import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { Provider } from "react-redux";
import "../data/";
import BlankLayout from "../src/layouts/BlankLayout";
import FullLayout from "../src/layouts/FullLayout";
import { store } from "../store/Store";
import "../styles/style.scss";

const layouts = {
  Blank: BlankLayout,
};

function MyApp({ Component, pageProps }) {
  const Layout = layouts[Component.layout] || FullLayout;
  return (
    <Provider store={store}>
      <Head>
        <title>AI Content Creator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SessionProvider session={pageProps.session}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </SessionProvider>
    </Provider>
  );
}

export default MyApp;
